from __future__ import annotations

from . import APP_NAME, APP_VERSION, CREATOR_CREDIT

MAX_BATCH_SIZE = 30
YOUTUBE_TITLE_LIMIT = 100
YOUTUBE_DESCRIPTION_LIMIT_BYTES = 5000
YOUTUBE_TAGS_LIMIT = 500
YOUTUBE_THUMBNAIL_LIMIT_BYTES = 2 * 1024 * 1024
YOUTUBE_UPLOAD_SCOPE = "https://www.googleapis.com/auth/youtube.upload"
DEFAULT_TIMEZONE = "Europe/Berlin"
DEFAULT_CATEGORY_ID = "10"  # Music
DEFAULT_SCHEDULE_DAYS = [1, 3, 4, 6]  # Tue, Thu, Fri, Sun
TRANSIENT_HTTP_STATUS = {500, 502, 503, 504}

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "CREATOR_CREDIT",
    "MAX_BATCH_SIZE",
    "YOUTUBE_TITLE_LIMIT",
    "YOUTUBE_DESCRIPTION_LIMIT_BYTES",
    "YOUTUBE_TAGS_LIMIT",
    "YOUTUBE_THUMBNAIL_LIMIT_BYTES",
]

